### PR TITLE
Support fasthttp

### LINKED ISSUE #12: Usage with fasthttp?
Is it somehow possible to use this package with [fasthttp](https://github.com/valyala/fasthttp) as HTTP wrapper in combination with [fasthttp-routing](github.com/qiangxue/fasthttp-routing)?

Because I really like the project and really want to integrate it into one of my projects which bases on these packages.

### PR DESCRIPTION
**Pull request by nupamore**
Fixes #12 

The implementation of websocket module for fastthtp is different. So, changing `sendStats` to public.
And added an example of a web framework `fiber` that uses fasthttp.

### CODE REVIEW

**Comment by arl** [comment]
Hey sorry for the delay.
Thank you for that PR.
I like the idea to present examples using various http libraries/routers but I'm not fond of having to change the public UI in order to accomodate a specific library.

I think it's acceptable to use fasthttp for the UI, but keep the `ws` handler as it is, statsviz already embeds a websocket implementation, which is gorilla's.
Also, statsviz is a debugging tool thats not going to be called /used as often as a, say, the public endpoints if a REST API, so performance doesn't matter as much. In other words, there's not a great added value in using a performance-minded library such as fasthttp for it, though I understand one doesn't want to mix routers on their server

**Comment by nupamore** [comment]
I fully agree with your opinion.  I think the least thing people want is the same port, not the same router.  I will consider how to use the built-in Gorilla WebSocket.

**Comment by nupamore** [comment]
The source is a bit esoteric, but I think it is best to maintain the performance of fasthttp without replacing the existing source.

**Comment by arl** [comment]
hey @nupamore thanks a lof for this PR.
Since the list of examples in the main readme.md keeps increasing with the many contributions I've receiving such as yours, I've moved the list of examples in a readme in the `_example` firectory. There would have been merge conflicts so I've merged your PR in a secondary branch to sort this out myself, didn't want to ask you to do that since there were no conflicts when you opened it, and that was a long time ago, sorry for the delay !
Your PR (and merge commit) is integrated in #51

**Comment by nupamore** [comment]
Thanks for not forgetting. But your `_example/Readme.md` links are broken. lol

**Comment by arl** [comment]
Thanks a lot for pointing that out 🙏🏽 @nupamore 
that's fixed now!

**Pull request merged**
