### PR TITLE
Revert "_example: add chi router"

### PR DESCRIPTION
**Pull request by arl**
Reverts arl/statsviz#29

### CODE REVIEW

**Comment by arl** [comment]
@dnnnvx I reverted your PR
the code compiles and the example runs, but then I can't get to the statsviz interface
by going to http://localhost:8080/debug/statsviz with my browser.

Did you test it?
How to do you access statsviz interface?

**Comment by arl** [comment]
Feel free to reopen a PR once this works.
thanks

**Comment by dnnnvx** [comment]
Sorry for that, I will try to fix this!

**Comment by arl** [comment]
No worries. Thank you

**Pull request merged**
