### PR TITLE
Fixed https

### PR DESCRIPTION
**Pull request by chicknsoup**
ws_prot not properly set to `wss` on sites using https

### CODE REVIEW

**Comment by arl** [comment]
Thank you for that.
It seems there was a problem with assets generation.
How did you do it?
The process is described in detail on CONTRIBUTING.md.

**Comment by chicknsoup** [comment]
> 
> 
> Thank you for that.
> It seems there was a problem with assets generation.
> How did you do it?
> The process is described in detail on CONTRIBUTING.md.

Hmm, I used `go generate` and that's what I get. How to fix the issue?

**Comment by arl** [comment]
You're right I see that in your last commit you regenerated the assets.
However, and I don't know why yet, the CI complains.
I'm gonna dig that up and maybe try to make that CI test more explicit about the failure.

In the meantime can you try to regenerate once and push again, just in case?
Thx

**Comment by arl** [comment]
@chicknsoup 
So I checked out your branch locally and indeed, for some reason it seems that the assets just need to be regenerated and pushed.

**Comment by chicknsoup** [comment]
It still complains. @.@

**Comment by arl** [comment]
@chicknsoup 
thanks
ok sorry for that. At this point I think that the CI step is off for some reason.
I need to look into that.

**Comment by arl** [comment]
@chicknsoup FYI I can confirm something is off with the CI step. 
I just pushed a copy of your branch myself and it passed.
So I'll let you know when I've fixed it.
thanks and sorry for that

**Comment by chicknsoup** [comment]
@arl Okay :)

**Comment by arl** [comment]
@chicknsoup 

Ok I thought the assets test passed in my branch (which is an exact copy of yours) but in fact it wasn't executed. There's a github action rule which conditions it to only run when the branch is `master`. It ran in your fork since you're indeed using `master` while it didn't in mine since I named the branch differently.

On my test branch, I removed that rule and pushed and indeed the assets test failed.
I don't know exactly what happens in your branch but I just regenerate and pushed and this was fixed (test passed again):

```
go generate # regenerate assets_vfsdata.go and modifies go.mod
go mod tidy
git rm --force go.sum # go.sum shouldn't be commited
# modified go.mod so that it shows go1.12 and not go1.15
git add assets_vfsdata.go
git add go.mod
git commit -m "regenerate assets"
git push
```

This should hopefully set your branch in the same state as mine (where all tests passed)

**Comment by arl** [comment]
@chicknsoup 
Once you have regenerated the assets and commited them, you can run locally:

```sh
.github/scripts/check_assets.sh
```
this will tell you assets have been correctly generated.

**Comment by chicknsoup** [comment]
> 
> 
> @chicknsoup
> Once you have regenerated the assets and commited them, you can run locally:
> 
> ```shell
> .github/scripts/check_assets.sh
> ```
> 
> this will tell you assets have been correctly generated.

Hmm, I'm using Windows, is it causing the issue?

**Comment by chicknsoup** [comment]
@arl I even switched to Ubuntu using wsl2, same issue

```
# .github/scripts/check_assets.sh
-                       uncompressedSize: 1406,
+                       uncompressedSize: 1407,
-                       compressedContent: []byte("\x1f\x8b\x08\x00\x00\x00\x00\x00\x02\xff\x84\x54\x41\x6f\xdb\x3a\x0c\xbe\xe7\x57\xb0\xc6\x3b\xc8\x6d\xa1\xf4\x5d\xde\xa1\x81\x1e\xb0\xb5\x3d\x74\x87\xad\x68\x30\xf4\x30\x0c\x85\x22\x33\x89\x50\x45\x32\x2c\xaa\x46\x31\xe4\xbf\x0f\xb4\x92\xd4\xf6\xbc\xcd\x17\x0b\xe6\xc7\x8f\x1f\x3f\x52\x16\xeb\xe4\x0d\xd9\xe0\x41\x94\xf0\x63\x06\x00\x70\xfa\xf2\x8f\xb0\xd5\xf1\x23\x3f\x0d\x52\x6a\x3c\x54\xc1\xa4\x1d\x7a\x92\x1b\xa4\x3b\x87\x7c\xfc\xf8\x76\x5f\x31\x78\xd1\x61\xf7\xb3\x21\xcf\x2a\x59\x57\x3d\xe1\x2a\x06\xf3\x82\xf4\xf5\xf1\x5e\xf4\x59\x5f\x75\x03\x2e\x18\x50\xd0\x5a\x5f\x85\x56\xba\x60\x34\xe7\x5d\x42\x1b\x9f\xeb\x26\x10\x28\x28\xda\x78\x5d\x2c\x4e\x39\x76\x0d\xc2\x05\x23\x39\x1a\x4c\x70\xa0\x94\x82\x62\x4b\x54\xc7\xeb\xa2\x4f\xce\x4f\x1b\x9f\x53\x63\x33\xc9\x80\x65\x3f\xee\xec\x58\xef\x02\x8a\xf9\xbc\x80\x0b\xd6\x25\xb7\x21\xd2\xe1\x58\x6b\xda\x7a\xbd\x43\x06\xb4\xb1\xe8\x37\x6b\x82\x8f\x04\x95\x26\xfd\x88\x84\x9e\xf5\x2f\xd1\x04\x5f\x45\x50\xf0\xdf\xd5\x22\xa3\xe6\xe7\xf0\x84\xab\x65\xe7\x03\x18\xed\xdc\x4a\x9b\x97\x08\xe7\xf3\x1c\x76\x48\x90\x4d\x02\x05\x1e\xdb\x77\xb0\x98\xf0\xf0\xe0\x36\x57\x0e\x0e\xa5\x0b\x1b\x51\x7c\x20\xc2\x5d\x4d\xd6\x6f\xe0\x26\x78\x8f\xdd\x00\xa4\x94\x45\x79\x50\x90\xf3\x65\xf0\xa1\x46\x0f\x8a\xa7\xae\xfe\xef\x19\x36\x60\x5b\x26\x63\x30\xc6\x75\x72\xee\xed\xc8\x87\x55\x71\x1c\xf3\x98\xd2\xb8\x10\x11\x14\xe0\x2b\x7a\xfa\x13\x6d\x6e\xf1\x86\xe1\x55\x4f\xe7\x35\x14\x97\x39\xb9\x7c\x1f\xd2\x81\x3d\xa2\xaf\x44\x71\xe3\x2c\x53\xe7\xcc\xb3\xa2\x9c\xd6\x81\x4d\x13\x1a\xd6\x91\xdf\x7f\xd3\x71\xc7\xb0\x5c\x9b\x4f\xa3\xee\x78\x3d\xad\xb7\x74\x1b\x3c\xf7\xb6\xd6\x2e\xe2\x62\x58\x6f\x87\x31\xea\xcd\x6f\x3a\xe7\x99\x6a\xe7\x96\xa4\x89\x57\xe1\xd3\xf2\xcb\x67\x59\xeb\x26\xa2\xe8\xc0\x92\x57\xa6\x1c\x2c\xf6\xd9\xb1\xdc\x78\x91\x23\x73\x48\x8e\x8a\xa9\x45\xbb\x3c\xd5\xe9\xd9\xd7\x91\xbe\xcb\xa7\x26\xe1\x30\x98\x57\xbf\x7f\x29\x4e\xc7\x54\x57\x9a\xb0\x63\x14\x23\xea\xf1\x15\x9f\x84\xf6\xe4\x67\xe9\x75\x8a\xdb\x5b\x4d\x5a\xf0\x6e\xdf\x6a\x42\x51\x0e\x44\x0f\x6c\x48\x56\xda\xf8\xa0\x53\xc4\x4a\x94\x63\x2b\xb2\xea\x29\xd1\xec\x37\xbb\x03\xea\x50\x34\x3a\x6b\x70\xd2\xb0\x72\xf8\x43\x61\x88\xdc\xa2\xae\xbf\x5d\x7d\x97\x0e\xfd\x86\xb6\xa0\x14\xfc\x3b\xae\x9d\xac\x34\x0d\x6a\xc2\x07\x17\x28\x76\x69\xe5\xd4\x4f\x25\x59\x99\x6d\xf9\x05\xb7\x9f\xcd\xf6\xdd\xfd\xfd\x19\x00\x00\xff\xff\x9f\x6e\x3c\x57\x7e\x05\x00\x00"),
+                       compressedContent: []byte("\x1f\x8b\x08\x00\x00\x00\x00\x00\x02\xff\x84\x54\x41\x6f\xdb\x3c\x0c\xbd\xe7\x57\xb0\xc2\x77\x90\xdb\x42\xe9\x77\xd9\xa1\x81\x06\x6c\x6d\x0f\xdd\x61\x2b\x1a\x0c\x3d\x0c\xc3\xa0\xc8\x4c\x22\x54\x91\x0c\x8b\x6a\x50\x0c\xf9\xef\x03\xad\x24\xb5\xbd\x6c\xf3\xc5\x82\xf9\xf8\xf8\xf8\x48\x59\x2e\x73\xb0\xe4\x62\x00\x59\xc1\xcf\x09\x00\xc0\xf1\xcb\x7f\xd2\xd5\x87\x8f\xfc\xb4\x48\xb9\x0d\x50\x47\x9b\x37\x18\x48\xad\x90\xee\x3c\xf2\xf1\xe3\xeb\x7d\xcd\xe0\x59\x87\xdd\x4d\x86\x3c\x8b\xec\x7c\xfd\x84\x8b\x14\xed\x33\xd2\xd7\xc7\x7b\xd9\x67\x7d\x31\x2d\xf8\x68\x41\xc3\xd6\x85\x3a\x6e\x95\x8f\xd6\x70\xde\x25\x6c\xd3\x8f\xa6\x8d\x04\x1a\xc4\x36\x5d\x8b\xd9\x31\xc7\x2d\x41\xfa\x68\x15\x47\xa3\x8d\x1e\xb4\xd6\x20\xd6\x44\x4d\xba\x16\x7d\x72\x7e\x06\x2c\x03\x9a\xdd\xb8\xb5\x03\xf4\x02\xc4\x74\x2a\xe0\x82\x85\xa9\x75\x4c\xb4\x3f\x36\x86\xd6\xc1\x6c\x90\x01\xdb\x24\xfa\xdd\xda\x18\x12\x41\x6d\xc8\x3c\x22\x61\xe0\x06\xe6\x68\x63\xa8\x13\x68\x78\x77\x35\x2b\xa8\xe9\x39\x3c\xe1\x62\xde\x19\x01\xd6\x78\xbf\x30\xf6\x39\xc1\xf9\xb4\x84\x3d\x12\x14\x97\x40\x43\xc0\xed\x1b\x58\x9e\x30\x71\x6f\x37\x57\x8e\x1e\x95\x8f\x2b\x29\x3e\x10\xe1\xa6\x21\x17\x56\x70\x13\x43\xc0\x6e\x02\x4a\x29\x51\xed\x15\x94\x7c\x15\x43\x6c\x30\x80\xe6\xb1\xeb\xf7\x3d\xc7\x06\x6c\xf3\x6c\x2d\xa6\xb4\xcc\xde\xbf\x1e\xf8\xb0\x16\x87\x39\x8f\x29\xad\x8f\x09\x41\x03\xbe\x60\xa0\xbf\xd1\x96\x16\x6f\x18\x5e\xf7\x74\x5e\x83\xb8\x2c\xc9\xd5\xdb\x90\xf6\xec\x09\x43\x2d\xc5\x8d\x77\x4c\x5d\x32\xcf\x44\x75\x5a\x07\xb6\x6d\x6c\x59\x47\x79\xff\x4b\xc7\x1d\xc3\x4a\x6d\x3e\x8d\xba\xe3\xfd\x74\xc1\xd1\x6d\x0c\xdc\xdb\xd2\xf8\x84\xb3\x61\xbd\x0d\xa6\x64\x56\x7f\xe8\x9c\x67\x6a\xbc\x9f\x93\x21\x5e\x85\x4f\xf3\x2f\x9f\x55\x63\xda\x84\xb2\x03\x2b\x5e\x99\x6a\xb0\xd9\x67\x87\x72\xe3\x4d\x4e\xcc\xa1\x38\x2a\x4f\x2d\xda\xe5\xb1\x4e\xcf\xbe\x8e\xf4\x4d\x3e\xb5\x19\x87\xc1\xb2\xfa\xfd\x4b\x71\x3c\xe6\xa6\x36\x84\x1d\xa3\x1c\x51\x8f\xef\xf8\x49\x68\x4f\x7e\x91\xde\xe4\xb4\xbe\x35\x64\x24\xef\xf6\xad\x21\x94\xd5\x40\xf4\xc0\x86\xec\x94\x4b\x0f\x26\x27\xac\x65\x35\xb6\xa2\xa8\x3e\x25\x9a\xfd\x66\x77\x40\xef\x8b\x26\xef\x2c\x9e\x34\xac\x1a\xfe\x51\x18\xa2\xd6\x68\x9a\x6f\x57\xdf\x95\xc7\xb0\xa2\x35\x68\x0d\xff\x8f\x6b\x67\xa7\x6c\x8b\x86\xf0\xc1\x47\x4a\x5d\x5a\x75\xea\xa7\x92\x9d\x2a\xb6\xfc\x86\xdb\x4d\x26\xbb\xee\xfe\xfe\x0a\x00\x00\xff\xff\x49\x13\xf9\x28\x7f\x05\x00\x00"),
assets_vfsdata.go is not up to date
```

@.@

**Comment by chicknsoup** [comment]
Oh wait, does this check make any sense? As we modified the file content, the `compressedContent` must be different between commits. So `git diff --unified=1 assets_vfsdata.go | grep -E '^(\+|\-)\s.*$' | grep -v modTime` should always return true.

**Comment by arl** [comment]
> Oh wait, does this check make any sense? As we modified the file content, the `compressedContent` must be different between commits. So `git diff --unified=1 assets_vfsdata.go | grep -E '^(\+|\-)\s.*$' | grep -v modTime` should always return true.

If you run `go generate` a first time, commit `assets_vfsdata.go` and then run `go generate` again, the content and compressed content will be the same, however `modtime` is different.

This script just compares that the only local differences are the `modtime` lines in `assets_vfsdata.go`.

**Comment by arl** [comment]
> @arl I even switched to Ubuntu using wsl2, same issue
> 
> ```
> # .github/scripts/check_assets.sh
> -                       uncompressedSize: 1406,
> +                       uncompressedSize: 1407,
> -                       compressedContent: []byte("\x1f\x8b\x08\x00\x00\x00\x00\x00\x02\xff\x84\x54\x41\x6f\xdb\x3a\x0c\xbe\xe7\x57\xb0\xc6\x3b\xc8\x6d\xa1\xf4\x5d\xde\xa1\x81\x1e\xb0\xb5\x3d\x74\x87\xad\x68\x30\xf4\x30\x0c\x85\x22\x33\x89\x50\x45\x32\x2c\xaa\x46\x31\xe4\xbf\x0f\xb4\x92\xd4\xf6\xbc\xcd\x17\x0b\xe6\xc7\x8f\x1f\x3f\x52\x16\xeb\xe4\x0d\xd9\xe0\x41\x94\xf0\x63\x06\x00\x70\xfa\xf2\x8f\xb0\xd5\xf1\x23\x3f\x0d\x52\x6a\x3c\x54\xc1\xa4\x1d\x7a\x92\x1b\xa4\x3b\x87\x7c\xfc\xf8\x76\x5f\x31\x78\xd1\x61\xf7\xb3\x21\xcf\x2a\x59\x57\x3d\xe1\x2a\x06\xf3\x82\xf4\xf5\xf1\x5e\xf4\x59\x5f\x75\x03\x2e\x18\x50\xd0\x5a\x5f\x85\x56\xba\x60\x34\xe7\x5d\x42\x1b\x9f\xeb\x26\x10\x28\x28\xda\x78\x5d\x2c\x4e\x39\x76\x0d\xc2\x05\x23\x39\x1a\x4c\x70\xa0\x94\x82\x62\x4b\x54\xc7\xeb\xa2\x4f\xce\x4f\x1b\x9f\x53\x63\x33\xc9\x80\x65\x3f\xee\xec\x58\xef\x02\x8a\xf9\xbc\x80\x0b\xd6\x25\xb7\x21\xd2\xe1\x58\x6b\xda\x7a\xbd\x43\x06\xb4\xb1\xe8\x37\x6b\x82\x8f\x04\x95\x26\xfd\x88\x84\x9e\xf5\x2f\xd1\x04\x5f\x45\x50\xf0\xdf\xd5\x22\xa3\xe6\xe7\xf0\x84\xab\x65\xe7\x03\x18\xed\xdc\x4a\x9b\x97\x08\xe7\xf3\x1c\x76\x48\x90\x4d\x02\x05\x1e\xdb\x77\xb0\x98\xf0\xf0\xe0\x36\x57\x0e\x0e\xa5\x0b\x1b\x51\x7c\x20\xc2\x5d\x4d\xd6\x6f\xe0\x26\x78\x8f\xdd\x00\xa4\x94\x45\x79\x50\x90\xf3\x65\xf0\xa1\x46\x0f\x8a\xa7\xae\xfe\xef\x19\x36\x60\x5b\x26\x63\x30\xc6\x75\x72\xee\xed\xc8\x87\x55\x71\x1c\xf3\x98\xd2\xb8\x10\x11\x14\xe0\x2b\x7a\xfa\x13\x6d\x6e\xf1\x86\xe1\x55\x4f\xe7\x35\x14\x97\x39\xb9\x7c\x1f\xd2\x81\x3d\xa2\xaf\x44\x71\xe3\x2c\x53\xe7\xcc\xb3\xa2\x9c\xd6\x81\x4d\x13\x1a\xd6\x91\xdf\x7f\xd3\x71\xc7\xb0\x5c\x9b\x4f\xa3\xee\x78\x3d\xad\xb7\x74\x1b\x3c\xf7\xb6\xd6\x2e\xe2\x62\x58\x6f\x87\x31\xea\xcd\x6f\x3a\xe7\x99\x6a\xe7\x96\xa4\x89\x57\xe1\xd3\xf2\xcb\x67\x59\xeb\x26\xa2\xe8\xc0\x92\x57\xa6\x1c\x2c\xf6\xd9\xb1\xdc\x78\x91\x23\x73\x48\x8e\x8a\xa9\x45\xbb\x3c\xd5\xe9\xd9\xd7\x91\xbe\xcb\xa7\x26\xe1\x30\x98\x57\xbf\x7f\x29\x4e\xc7\x54\x57\x9a\xb0\x63\x14\x23\xea\xf1\x15\x9f\x84\xf6\xe4\x67\xe9\x75\x8a\xdb\x5b\x4d\x5a\xf0\x6e\xdf\x6a\x42\x51\x0e\x44\x0f\x6c\x48\x56\xda\xf8\xa0\x53\xc4\x4a\x94\x63\x2b\xb2\xea\x29\xd1\xec\x37\xbb\x03\xea\x50\x34\x3a\x6b\x70\xd2\xb0\x72\xf8\x43\x61\x88\xdc\xa2\xae\xbf\x5d\x7d\x97\x0e\xfd\x86\xb6\xa0\x14\xfc\x3b\xae\x9d\xac\x34\x0d\x6a\xc2\x07\x17\x28\x76\x69\xe5\xd4\x4f\x25\x59\x99\x6d\xf9\x05\xb7\x9f\xcd\xf6\xdd\xfd\xfd\x19\x00\x00\xff\xff\x9f\x6e\x3c\x57\x7e\x05\x00\x00"),
> +                       compressedContent: []byte("\x1f\x8b\x08\x00\x00\x00\x00\x00\x02\xff\x84\x54\x41\x6f\xdb\x3c\x0c\xbd\xe7\x57\xb0\xc2\x77\x90\xdb\x42\xe9\x77\xd9\xa1\x81\x06\x6c\x6d\x0f\xdd\x61\x2b\x1a\x0c\x3d\x0c\xc3\xa0\xc8\x4c\x22\x54\x91\x0c\x8b\x6a\x50\x0c\xf9\xef\x03\xad\x24\xb5\xbd\x6c\xf3\xc5\x82\xf9\xf8\xf8\xf8\x48\x59\x2e\x73\xb0\xe4\x62\x00\x59\xc1\xcf\x09\x00\xc0\xf1\xcb\x7f\xd2\xd5\x87\x8f\xfc\xb4\x48\xb9\x0d\x50\x47\x9b\x37\x18\x48\xad\x90\xee\x3c\xf2\xf1\xe3\xeb\x7d\xcd\xe0\x59\x87\xdd\x4d\x86\x3c\x8b\xec\x7c\xfd\x84\x8b\x14\xed\x33\xd2\xd7\xc7\x7b\xd9\x67\x7d\x31\x2d\xf8\x68\x41\xc3\xd6\x85\x3a\x6e\x95\x8f\xd6\x70\xde\x25\x6c\xd3\x8f\xa6\x8d\x04\x1a\xc4\x36\x5d\x8b\xd9\x31\xc7\x2d\x41\xfa\x68\x15\x47\xa3\x8d\x1e\xb4\xd6\x20\xd6\x44\x4d\xba\x16\x7d\x72\x7e\x06\x2c\x03\x9a\xdd\xb8\xb5\x03\xf4\x02\xc4\x74\x2a\xe0\x82\x85\xa9\x75\x4c\xb4\x3f\x36\x86\xd6\xc1\x6c\x90\x01\xdb\x24\xfa\xdd\xda\x18\x12\x41\x6d\xc8\x3c\x22\x61\xe0\x06\xe6\x68\x63\xa8\x13\x68\x78\x77\x35\x2b\xa8\xe9\x39\x3c\xe1\x62\xde\x19\x01\xd6\x78\xbf\x30\xf6\x39\xc1\xf9\xb4\x84\x3d\x12\x14\x97\x40\x43\xc0\xed\x1b\x58\x9e\x30\x71\x6f\x37\x57\x8e\x1e\x95\x8f\x2b\x29\x3e\x10\xe1\xa6\x21\x17\x56\x70\x13\x43\xc0\x6e\x02\x4a\x29\x51\xed\x15\x94\x7c\x15\x43\x6c\x30\x80\xe6\xb1\xeb\xf7\x3d\xc7\x06\x6c\xf3\x6c\x2d\xa6\xb4\xcc\xde\xbf\x1e\xf8\xb0\x16\x87\x39\x8f\x29\xad\x8f\x09\x41\x03\xbe\x60\xa0\xbf\xd1\x96\x16\x6f\x18\x5e\xf7\x74\x5e\x83\xb8\x2c\xc9\xd5\xdb\x90\xf6\xec\x09\x43\x2d\xc5\x8d\x77\x4c\x5d\x32\xcf\x44\x75\x5a\x07\xb6\x6d\x6c\x59\x47\x79\xff\x4b\xc7\x1d\xc3\x4a\x6d\x3e\x8d\xba\xe3\xfd\x74\xc1\xd1\x6d\x0c\xdc\xdb\xd2\xf8\x84\xb3\x61\xbd\x0d\xa6\x64\x56\x7f\xe8\x9c\x67\x6a\xbc\x9f\x93\x21\x5e\x85\x4f\xf3\x2f\x9f\x55\x63\xda\x84\xb2\x03\x2b\x5e\x99\x6a\xb0\xd9\x67\x87\x72\xe3\x4d\x4e\xcc\xa1\x38\x2a\x4f\x2d\xda\xe5\xb1\x4e\xcf\xbe\x8e\xf4\x4d\x3e\xb5\x19\x87\xc1\xb2\xfa\xfd\x4b\x71\x3c\xe6\xa6\x36\x84\x1d\xa3\x1c\x51\x8f\xef\xf8\x49\x68\x4f\x7e\x91\xde\xe4\xb4\xbe\x35\x64\x24\xef\xf6\xad\x21\x94\xd5\x40\xf4\xc0\x86\xec\x94\x4b\x0f\x26\x27\xac\x65\x35\xb6\xa2\xa8\x3e\x25\x9a\xfd\x66\x77\x40\xef\x8b\x26\xef\x2c\x9e\x34\xac\x1a\xfe\x51\x18\xa2\xd6\x68\x9a\x6f\x57\xdf\x95\xc7\xb0\xa2\x35\x68\x0d\xff\x8f\x6b\x67\xa7\x6c\x8b\x86\xf0\xc1\x47\x4a\x5d\x5a\x75\xea\xa7\x92\x9d\x2a\xb6\xfc\x86\xdb\x4d\x26\xbb\xee\xfe\xfe\x0a\x00\x00\xff\xff\x49\x13\xf9\x28\x7f\x05\x00\x00"),
> assets_vfsdata.go is not up to date
> ```
> 
> @.@

At the end of the day this script only runs `git diff` and analyzes the differences if there are any, and it seems there are differences in your working copy, hence the script output above.
Actually I uncompressed the bytes in `compressedContent` and I'm very much confused now since these are the differences
that should have been commited (it's your modification in `static/app.js`).

Can you run git status and git diff in your terminal?

**Comment by chicknsoup** [comment]
Now it passed.

**Comment by arl** [comment]
Merged!
I'm gonna update the CHANGELOG and push a new PATCH version including your changes.
Thanks again

**Pull request merged**
