### PR TITLE
Improve the problem of lagging or even OOM caused by reactivation after hanging in the background for a long time

### PR DESCRIPTION
**Pull request by mzzsfy**

### CODE REVIEW

**Comment by arl** [comment]
Hi and thank you for contributing 
Can you say a bit more about the issue and explain the solution you implemented to resolve it.

**Comment by mzzsfy** [comment]
When your page is in the background for a long time (minutes or even hours, Chrome), the callback of websocket.onmessage will not be processed on time. When the page is reactivated, onmessage is called repeatedly, which will generate a large number of UI redraw, which will cause the page to freeze or even OOM
My solution is to separate the ui redrawing from the onmessage method and use the setInterval method to render the ui separately. When onmessage is called repeatedly, a large number of ui redrawing will not occur.

**Comment by arl** [comment]
I see, thank you very much.

**Comment by mzzsfy** [comment]
Nice, so when will this be released to the next version? I have encountered this problem many times. In the worst case, I need to use the task manager to forcefully close chrome.

**Comment by arl** [comment]
> Nice, so when will this be released to the next version?

As soon as I've got the time to try your PR, merge it and tag a release. I hope to have time today, or else it's going to be during the weekend

**Comment by mzzsfy** [comment]
I see, thank you very much.

**Comment by arl** [comment]
I've tried to reproduce the problem you were having but I couldn't.
Can you detail the steps needed to reproduce it please?

**Comment by mzzsfy** [comment]
Windows systems,open web page, use Microsoft Edge and play the video in full screen. It will take about a few minutes to reproduce the problem(Make sure the energy -saving mode is not closed).If you still can't reproduce this scenario, I will submit an issue

**Comment by mzzsfy** [comment]
Already solved https://github.com/arl/statsviz/pull/122

**Pull request closed without merging**
